#!/usr/bin/env python3

import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522
import vlc
import time

reader = SimpleMFRC522()

# RFID -> media files
visual_files = {
    551721708274: "/home/campse/caps/env/one.mp4",
    207537121893: "/home/campse/caps/env/two.mp4",
    482431805988: "/home/campse/caps/env/three.mp3"
}

# Stop card
stop_card = 1031617194694

# Looping video
looping_video = "/home/campse/caps/env/loop.mp4"

# Create ONE VLC player
instance = vlc.Instance('--fullscreen', '--no-video-title-show')
player = instance.media_player_new()

def play_media(file):
    media = instance.media_new(file)
    player.set_media(media)
    player.play()

try:
    # Start looping video
    play_media(looping_video)

    while True:
        id = reader.read()[0]

        # Stop card
        if id == stop_card:
            break

        if id in visual_files:
            file_path = visual_files[id]

            # Play clue instantly (no flicker)
            play_media(file_path)

            # Wait until media finishes
            time.sleep(1)
            while player.is_playing():
                time.sleep(0.5)

            # Return to loop
            play_media(looping_video)

        time.sleep(0.2)

finally:
    GPIO.cleanup()
    player.stop()
